name: Build and Deploy (Godot 4 HTML5)

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Godot 4.3 + export templates (robust)
        run: |
          set -e
          VER=4.3
          BASE="https://downloads.tuxfamily.org/godotengine/${VER}"
          # Use the **editor** zip (always present). We'll still run it with --headless.
          wget -q "${BASE}/Godot_v${VER}-stable_linux.x86_64.zip" -O godot.zip
          wget -q "${BASE}/Godot_v${VER}-stable_export_templates.tpz" -O templates.tpz

          mkdir -p "$HOME/godot"
          unzip -q godot.zip -d "$HOME/godot"

          # Install export templates to the standard location for Godot 4.x
          mkdir -p "$HOME/.local/share/godot/export_templates/${VER}.stable"
          unzip -q templates.tpz -d "$HOME/.local/share/godot/export_templates/${VER}.stable"

          # Find the extracted binary (name can vary slightly), make it executable, and expose it to later steps
          GODOT_BIN="$(find "$HOME/godot" -maxdepth 1 -type f -name "Godot_v${VER}-stable_*" | head -n1)"
          chmod +x "$GODOT_BIN"
          echo "GODOT_BIN=$GODOT_BIN" >> "$GITHUB_ENV"

          echo "Installed Godot at: $GODOT_BIN"
          "$GODOT_BIN" --version || true

      - name: Export HTML5
        run: |
          set -e
          mkdir -p build/web
          echo "Using Godot: $GODOT_BIN"
          "$GODOT_BIN" --headless --export-release "Web" build/web/index.html --verbose

      - name: Upload Pages Artifact
        uses:   actions/upload-pages-artifact@v3
        with:
          path: build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
