name: Build and Deploy (Godot 4 HTML5)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Godot 4
        uses: chickensoft-games/setup-godot@v2
        with:
          version: "4.3"
          use-dotnet: false
          export-templates: true

      - name: Export HTML5
        run: |
          mkdir -p build/web
          godot --headless --export-release "Web" build/web/index.html

      - name: Upload artifact for PRs
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web/

      - name: Upload Pages Artifact (main)
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/upload-pages-artifact@v2
        with:
          path: build/web/

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4
