name: Sanity CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "CI is alive ✅"

