name: Pages Minimal

on:
  push:
    branches: ["main"]
    paths:
      - "scenes/**"
      - "export_presets.cfg"
      - ".github/workflows/pages-min.yml"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-min
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "<!doctype html><title>ping</title><h1>Ping 🌱</h1>" > index.html
          mkdir -p build/web
          cp index.html build/web/index.html
      - uses: actions/upload-pages-artifact@v2
        with:
          path: build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4
